edition = "2024"
max_width = 100

#doc_comment_code_block_width = 100
#format_code_in_doc_comments = true
use_field_init_shorthand = true
newline_style = "Unix"
#reorder_impl_items = true
#wrap_comments = true
