[build]
incremental = true

[alias]
ci = "fmt --check --all && run -- clippy --all-targets --all-features -- -D warnings && run -- test"

[profile.release]
panic = "abort"
strip = true
opt-level = 3
lto = "thin"
debug = "line-tables-only"
codegen-units = 16

[profile.profiling]
inherits = "release"
debug = 2
debug-assertions = false
strip = false
